/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.Color;
import CustomComponents.*;
import javax.swing.text.MaskFormatter;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JTextField;

/**
 *
 * @author PC
 */
public class Jfacturacion extends javax.swing.JFrame {

    /**
     * Creates new form Jfacturacion
     */
    public Jfacturacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaGrid = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        rbTodos = new javax.swing.JRadioButton();
        rbContado = new javax.swing.JRadioButton();
        rbCredito = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        rbTodosConsul = new javax.swing.JRadioButton();
        rbConsultado = new javax.swing.JRadioButton();
        rbNoConsultado = new javax.swing.JRadioButton();
        txtHoraFinal = new javax.swing.JFormattedTextField();
        txtFechafinal = new com.toedter.calendar.JDateChooser("dd/MM/yyyy","##/##/####", '_');
        txtFechainicial = new com.toedter.calendar.JDateChooser("dd/MM/yyyy","##/##/####", '_');
        txtHoraInicial = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbMoneda1Total4 = new javax.swing.JLabel();
        cmbDE = new javax.swing.JComboBox();
        cmbEstados = new javax.swing.JComboBox();
        lbMoneda1Total2 = new javax.swing.JLabel();
        lbMoneda1Total5 = new javax.swing.JLabel();
        cmbSituacion = new javax.swing.JComboBox();
        btnBuscar = new CustomButtom();
        chkReenviar = new javax.swing.JCheckBox();
        chkRegenrarNumF = new javax.swing.JCheckBox();
        lbCantSeleccionada = new javax.swing.JLabel();
        lbMoneda1Total3 = new javax.swing.JLabel();
        btnCancelar = new CustomButtom();
        btnProcesar = new CustomButtom();
        jPanel3 = new javax.swing.JPanel();
        btnSalir = new CustomButtom();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tablaGrid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablaGrid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NRO. DE VENTA", "FECHA DE EMISION", "TIP. DE VENTA", "DOCUMENTO", "CLIENTE", "TOTAL DE FACT.", "F. C", "NRO. FACT.", "CDC", "ESTADO", "MENSAJE", "COD. MENSAJE", "CONSULTADO", "PROCESAR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaGrid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaGridMouseClicked(evt);
            }
        });
        tablaGrid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaGridKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaGrid);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbTodos.setBackground(new java.awt.Color(255, 255, 255));
        rbTodos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbTodos.setText("TODOS");
        rbTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTodosActionPerformed(evt);
            }
        });
        jPanel5.add(rbTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 85, 19));

        rbContado.setBackground(new java.awt.Color(255, 255, 255));
        rbContado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbContado.setText("CONTADO");
        jPanel5.add(rbContado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 1, 85, 19));

        rbCredito.setBackground(new java.awt.Color(255, 255, 255));
        rbCredito.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbCredito.setText("CREDITO");
        rbCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCreditoActionPerformed(evt);
            }
        });
        jPanel5.add(rbCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1, 90, 19));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbTodosConsul.setBackground(new java.awt.Color(255, 255, 255));
        rbTodosConsul.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbTodosConsul.setSelected(true);
        rbTodosConsul.setText("TODOS");
        rbTodosConsul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTodosConsulActionPerformed(evt);
            }
        });
        jPanel6.add(rbTodosConsul, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 85, 19));

        rbConsultado.setBackground(new java.awt.Color(255, 255, 255));
        rbConsultado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbConsultado.setText("CONSULTADO");
        jPanel6.add(rbConsultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 1, 100, 19));

        rbNoConsultado.setBackground(new java.awt.Color(255, 255, 255));
        rbNoConsultado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbNoConsultado.setText("NO. CONSULTADO");
        rbNoConsultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNoConsultadoActionPerformed(evt);
            }
        });
        jPanel6.add(rbNoConsultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 1, 130, 19));

        try{
            MaskFormatter mascara = new MaskFormatter("##:##");
            txtHoraFinal = new javax.swing.JFormattedTextField(mascara);
        }catch(Exception e){
        }
        txtHoraFinal.setBackground(new java.awt.Color(153, 204, 255));
        txtHoraFinal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtHoraFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHoraFinal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtHoraFinal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtHoraFinalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHoraFinalFocusLost(evt);
            }
        });
        txtHoraFinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHoraFinalKeyPressed(evt);
            }
        });

        txtFechafinal.setBackground(new java.awt.Color(153, 204, 255));
        txtFechafinal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFechafinal.setDateFormatString("dd/MM/yyyy");
        txtFechafinal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFechafinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFechafinalKeyPressed(evt);
            }
        });

        txtFechainicial.setBackground(new java.awt.Color(153, 204, 255));
        txtFechainicial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFechainicial.setDateFormatString("dd/MM/yyyy");
        txtFechainicial.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFechainicial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFechainicialFocusGained(evt);
            }
        });
        txtFechainicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFechainicialKeyPressed(evt);
            }
        });

        try{
            MaskFormatter mascara = new MaskFormatter("##:##");
            txtHoraInicial = new javax.swing.JFormattedTextField(mascara);
        }catch(Exception e){
        }
        txtHoraInicial.setBackground(new java.awt.Color(153, 204, 255));
        txtHoraInicial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtHoraInicial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHoraInicial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtHoraInicial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtHoraInicialFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHoraInicialFocusLost(evt);
            }
        });
        txtHoraInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHoraInicialKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("DESDE:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("HASTA:");

        lbMoneda1Total4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbMoneda1Total4.setText("DE TIPO:");

        cmbDE.setBackground(new java.awt.Color(153, 204, 255));
        cmbDE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbDE.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FACTURA", "NOTA DE CREDITO", "EVENTOS" }));
        cmbDE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmbDE.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDEItemStateChanged(evt);
            }
        });

        cmbEstados.setBackground(new java.awt.Color(153, 204, 255));
        cmbEstados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbEstados.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TODOS", "NO APROBADOS", "Aprobado", "Rechazado", "Otros", "No Procesado" }));
        cmbEstados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbMoneda1Total2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbMoneda1Total2.setText("ESTADO:");

        lbMoneda1Total5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbMoneda1Total5.setText("SITUACION:");

        cmbSituacion.setBackground(new java.awt.Color(153, 204, 255));
        cmbSituacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbSituacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TODOS", "0   | GENERADO", "1   | EN COLA", "2   | APROBADO", "3   | APROBADO OBS", "4   | RECHAZADO", "98 | NO EXISTE", "99 | CANCELADO" }));
        cmbSituacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon-buscar.png"))); // NOI18N
        btnBuscar.setText("F2: BUSCAR");
        btnBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        btnBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnBuscarKeyPressed(evt);
            }
        });

        chkReenviar.setBackground(new java.awt.Color(255, 255, 255));
        chkReenviar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkReenviar.setText("FORZAR REENVIOS");

        chkRegenrarNumF.setBackground(new java.awt.Color(255, 255, 255));
        chkRegenrarNumF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkRegenrarNumF.setText("RENUMERAR FACTURA");
        chkRegenrarNumF.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkRegenrarNumFItemStateChanged(evt);
            }
        });
        chkRegenrarNumF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRegenrarNumFActionPerformed(evt);
            }
        });

        lbCantSeleccionada.setBackground(new java.awt.Color(153, 204, 255));
        lbCantSeleccionada.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbCantSeleccionada.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbCantSeleccionada.setText("0");
        lbCantSeleccionada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbCantSeleccionada.setOpaque(true);

        lbMoneda1Total3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbMoneda1Total3.setText("CANT. SELEC.:");

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon-cancelar.png"))); // NOI18N
        btnCancelar.setText("F8: CANCELAR");
        btnCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        btnCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCancelarKeyPressed(evt);
            }
        });

        btnProcesar.setBackground(new java.awt.Color(255, 255, 255));
        btnProcesar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnProcesar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon-confirmar.png"))); // NOI18N
        btnProcesar.setText("F5: PROCESAR");
        btnProcesar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        btnProcesar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });
        btnProcesar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnProcesarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechainicial, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechafinal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtHoraInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMoneda1Total3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCantSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chkReenviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chkRegenrarNumF, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbDE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMoneda1Total4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbMoneda1Total2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(cmbSituacion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lbMoneda1Total5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(chkRegenrarNumF, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(lbMoneda1Total3)
                            .addGap(6, 6, 6)
                            .addComponent(lbCantSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkReenviar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtFechainicial, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(txtFechafinal, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHoraInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txtHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbMoneda1Total4)
                                    .addComponent(lbMoneda1Total2))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbDE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lbMoneda1Total5)
                                .addGap(9, 9, 9)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbSituacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );

        ((JTextField) txtFechafinal.getDateEditor().getUiComponent()).addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent e) {
                if (e.getKeyChar()==e.VK_ENTER) {
                    txtHoraFinal.requestFocus();
                }
                botonGen(e);
            }
        });
        ((JTextField) txtFechainicial.getDateEditor().getUiComponent()).addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent e) {
                if (e.getKeyChar()==e.VK_ENTER) {
                    txtHoraInicial.requestFocus();
                }
                botonGen(e);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon-salir.png"))); // NOI18N
        btnSalir.setText("F11: SALIR");
        btnSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        btnSalir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSalirKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaGridMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaGridMouseClicked

    }//GEN-LAST:event_tablaGridMouseClicked

    private void tablaGridKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaGridKeyPressed
     
    }//GEN-LAST:event_tablaGridKeyPressed

    private void rbTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbTodosActionPerformed

    private void rbCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCreditoActionPerformed

    private void rbTodosConsulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTodosConsulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbTodosConsulActionPerformed

    private void rbNoConsultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNoConsultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNoConsultadoActionPerformed

    private void txtHoraFinalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHoraFinalFocusGained
        txtHoraFinal.setBackground(new Color(67, 243, 17));
        txtHoraFinal.setText(txtHoraFinal.getText());
        txtHoraFinal.selectAll();
    }//GEN-LAST:event_txtHoraFinalFocusGained

    private void txtHoraFinalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHoraFinalFocusLost
        if (txtHoraFinal.getText().equals("  :  ")) {
            txtHoraFinal.setValue(null);
        }
        txtHoraFinal.setBackground(new Color(153, 204, 255));
    }//GEN-LAST:event_txtHoraFinalFocusLost

    private void txtHoraFinalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoraFinalKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnBuscar.requestFocus();
        }
        botonGen(evt);
    }//GEN-LAST:event_txtHoraFinalKeyPressed

    private void txtFechafinalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechafinalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechafinalKeyPressed

    private void txtFechainicialFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFechainicialFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechainicialFocusGained

    private void txtFechainicialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechainicialKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechainicialKeyPressed

    private void txtHoraInicialFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHoraInicialFocusGained
        txtHoraInicial.setBackground(new Color(67, 243, 17));
        txtHoraInicial.setText(txtHoraInicial.getText());
        txtHoraInicial.selectAll();
    }//GEN-LAST:event_txtHoraInicialFocusGained

    private void txtHoraInicialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHoraInicialFocusLost
        ///System.out.println(txtFechainicial1.getText());
        if (txtHoraInicial.getText().equals("  :  ")) {
            ///txtFechainicial1.setValue("    ");
            txtHoraInicial.setValue(null);
        }
        txtHoraInicial.setBackground(new Color(153, 204, 255));
    }//GEN-LAST:event_txtHoraInicialFocusLost

    private void txtHoraInicialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoraInicialKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtHoraFinal.requestFocus();
        }
        botonGen(evt);
    }//GEN-LAST:event_txtHoraInicialKeyPressed

    private void cmbDEItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDEItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDEItemStateChanged

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // busca();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBuscarKeyPressed
        botonGen(evt);
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnBuscar.doClick();
        }
    }//GEN-LAST:event_btnBuscarKeyPressed

    private void chkRegenrarNumFItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkRegenrarNumFItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_chkRegenrarNumFItemStateChanged

    private void chkRegenrarNumFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRegenrarNumFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkRegenrarNumFActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCancelarKeyPressed
        botonGen(evt);
    }//GEN-LAST:event_btnCancelarKeyPressed

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed

    }//GEN-LAST:event_btnProcesarActionPerformed

    private void btnProcesarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnProcesarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProcesarKeyPressed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSalirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalirKeyPressed
        botonGen(evt);
    }//GEN-LAST:event_btnSalirKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jfacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jfacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jfacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jfacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jfacturacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnProcesar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox chkReenviar;
    private javax.swing.JCheckBox chkRegenrarNumF;
    private javax.swing.JComboBox cmbDE;
    private javax.swing.JComboBox cmbEstados;
    private javax.swing.JComboBox cmbSituacion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCantSeleccionada;
    private javax.swing.JLabel lbMoneda1Total2;
    private javax.swing.JLabel lbMoneda1Total3;
    private javax.swing.JLabel lbMoneda1Total4;
    private javax.swing.JLabel lbMoneda1Total5;
    private javax.swing.JRadioButton rbConsultado;
    private javax.swing.JRadioButton rbContado;
    private javax.swing.JRadioButton rbCredito;
    private javax.swing.JRadioButton rbNoConsultado;
    private javax.swing.JRadioButton rbTodos;
    private javax.swing.JRadioButton rbTodosConsul;
    private javax.swing.JTable tablaGrid;
    private com.toedter.calendar.JDateChooser txtFechafinal;
    private com.toedter.calendar.JDateChooser txtFechainicial;
    private javax.swing.JFormattedTextField txtHoraFinal;
    private javax.swing.JFormattedTextField txtHoraInicial;
    // End of variables declaration//GEN-END:variables


    private void botonGen(KeyEvent evt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
